#! /bin/bash

arduino-cli compile --fqbn arduino:avr:mega ~/REMS-RTA/REMS/REMS2/sensorTest/sensorTest.ino
arduino-cli upload -p /dev/ttyACM1 --fqbn arduino:avr:mega ~/REMS-RTA/REMS/REMS2/sensorTest/sensorTest.ino
